# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    networks: 
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks: 
      - mongo-compose-network

  nodebackend:
    build: ./backend
    ports:
      - "4200:4200"
    volumes:
      - ./backend:/home/node/app
      - ./backend/node_modules:/home/node/app/node_modules
    environment:
      - NODE_ENV=development
      - CI=true
    depends_on:
      - mongo
    networks: 
      - mongo-compose-network

  # react:
  #   build: 
  #     dockerfile: ./react.dockerfile
  #     context: ./frontend
  #   volumes:
  #     - './frontend:/app'
  #     - '/app/node_modules'
  #   environment:
  #     - NODE_ENV=development
  #     - CI=true
  #   ports:
  #     - 3001:3000

  
networks: 
  mongo-compose-network:
    driver: bridge